---
- name: Include firewall.yml
  include_vars: "vars/firewall.yml"
  tags:
    - "firewall"

  #Install firewalld and enable it
- name: Install firewalld
  become: yes
  yum:
    name: "firewalld"
    state: "present"
  ignore_errors: yes
  tags:
    - "firewall"

- name: Set hostname with hostnamectl
  hostname:
    name: "{{ satellite_deployment_hostname_full }}"
  tags:
    - "firewall"

- name: Update /etc/hosts with satellite hostname
  lineinfile:
    line: "{{ satellite_deployment_ip_address }}
      {{ satellite_deployment_hostname_full }}
      {{ satellite_deployment_hostname_short }}"
    dest: "/etc/hosts"
  tags:
    - "firewall"

- name: Enable Firewalld (and unmask if necessary)
  become: yes
  service:
    enabled: yes
    masked: no
    name: firewalld
    state: started
  when: not satellite_mask_firewalld
  tags:
    - "firewall"

#Opening firewall ports
- name: Firewall and hostname | Opening Firewalld ports
  become: yes
  firewalld:
    permanent: yes
    immediate: yes
    port: "{{ item }}"
    state: "enabled"
  with_items: "{{ satellite_deployment_fw_ports + satellite_deployment_plugin_ports }}"
  ignore_errors: yes
  tags:
    - "firewall"

- name: stop Firewalld if necessary
  become: yes
  systemd:
    state: stopped
    name: firewalld
  when: satellite_mask_firewalld
  tags:
    - "firewall"

- name: mask Firewalld if necessary
  become: yes
  systemd:
    enabled: no
    masked: yes
    name: firewalld.service
  when: satellite_mask_firewalld
  tags:
    - "firewall"